baseURL = 'https://remix.roneo.app/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'


[params]
  title = 'Remix, a theme for Hugo fully editable with Netlify CMS'
  metaDescription = "Here is the meta description"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 2
mark = "FR"


[taxonomies]
  category= "categories"
  scene = "scenes"
