baseURL = 'https://remix.roneo.app/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Remix, a theme for Hugo fully editable with Netlify CMS'
  metaDescription = "Here is the meta description"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.zh]
languageName = "中文"
languageCode = "zh-zh"
contentDir = "content/chinese"
weight = 2
mark = "中"


[taxonomies]
  category= "categories"
  scene = "scenes"
